<?xml version="1.0"?>
<page id="Gio.IOErrorEnum"
      type="guide"
      style="enum"
      xmlns="http://projectmallard.org/1.0/"
      xmlns:api="http://projectmallard.org/experimental/api/"
      xmlns:ui="http://projectmallard.org/1.0/ui/">
  <info>
    <link xref="index" group="enum" type="guide"/>
  </info>
  <title>Gio.IOErrorEnum</title>
  <p>Error codes returned by GIO functions.</p>

<terms>
<item>
<title><code>IOErrorEnum.FAILED</code></title>
  <p>Generic error condition for when any operation fails.</p>
</item>
<item>
<title><code>IOErrorEnum.NOT_FOUND</code></title>
  <p>File not found.</p>
</item>
<item>
<title><code>IOErrorEnum.EXISTS</code></title>
  <p>File already exists.</p>
</item>
<item>
<title><code>IOErrorEnum.IS_DIRECTORY</code></title>
  <p>File is a directory.</p>
</item>
<item>
<title><code>IOErrorEnum.NOT_DIRECTORY</code></title>
  <p>File is not a directory.</p>
</item>
<item>
<title><code>IOErrorEnum.NOT_EMPTY</code></title>
  <p>File is a directory that isn't empty.</p>
</item>
<item>
<title><code>IOErrorEnum.NOT_REGULAR_FILE</code></title>
  <p>File is not a regular file.</p>
</item>
<item>
<title><code>IOErrorEnum.NOT_SYMBOLIC_LINK</code></title>
  <p>File is not a symbolic link.</p>
</item>
<item>
<title><code>IOErrorEnum.NOT_MOUNTABLE_FILE</code></title>
  <p>File cannot be mounted.</p>
</item>
<item>
<title><code>IOErrorEnum.FILENAME_TOO_LONG</code></title>
  <p>Filename is too many characters.</p>
</item>
<item>
<title><code>IOErrorEnum.INVALID_FILENAME</code></title>
  <p>Filename is invalid or contains invalid characters.</p>
</item>
<item>
<title><code>IOErrorEnum.TOO_MANY_LINKS</code></title>
  <p>File contains too many symbolic links.</p>
</item>
<item>
<title><code>IOErrorEnum.NO_SPACE</code></title>
  <p>No space left on drive.</p>
</item>
<item>
<title><code>IOErrorEnum.INVALID_ARGUMENT</code></title>
  <p>Invalid argument.</p>
</item>
<item>
<title><code>IOErrorEnum.PERMISSION_DENIED</code></title>
  <p>Permission denied.</p>
</item>
<item>
<title><code>IOErrorEnum.NOT_SUPPORTED</code></title>
  <p>Operation not supported for the current backend.</p>
</item>
<item>
<title><code>IOErrorEnum.NOT_MOUNTED</code></title>
  <p>File isn't mounted.</p>
</item>
<item>
<title><code>IOErrorEnum.ALREADY_MOUNTED</code></title>
  <p>File is already mounted.</p>
</item>
<item>
<title><code>IOErrorEnum.CLOSED</code></title>
  <p>File was closed.</p>
</item>
<item>
<title><code>IOErrorEnum.CANCELLED</code></title>
  <p>Operation was cancelled. See <link xref="Gio.Cancellable"/>.</p>
</item>
<item>
<title><code>IOErrorEnum.PENDING</code></title>
  <p>Operations are still pending.</p>
</item>
<item>
<title><code>IOErrorEnum.READ_ONLY</code></title>
  <p>File is read only.</p>
</item>
<item>
<title><code>IOErrorEnum.CANT_CREATE_BACKUP</code></title>
  <p>Backup couldn't be created.</p>
</item>
<item>
<title><code>IOErrorEnum.WRONG_ETAG</code></title>
  <p>File's Entity Tag was incorrect.</p>
</item>
<item>
<title><code>IOErrorEnum.TIMED_OUT</code></title>
  <p>Operation timed out.</p>
</item>
<item>
<title><code>IOErrorEnum.WOULD_RECURSE</code></title>
  <p>Operation would be recursive.</p>
</item>
<item>
<title><code>IOErrorEnum.BUSY</code></title>
  <p>File is busy.</p>
</item>
<item>
<title><code>IOErrorEnum.WOULD_BLOCK</code></title>
  <p>Operation would block.</p>
</item>
<item>
<title><code>IOErrorEnum.HOST_NOT_FOUND</code></title>
  <p>Host couldn't be found (remote operations).</p>
</item>
<item>
<title><code>IOErrorEnum.WOULD_MERGE</code></title>
  <p>Operation would merge files.</p>
</item>
<item>
<title><code>IOErrorEnum.FAILED_HANDLED</code></title>
  <p>Operation failed and a helper program has
    already interacted with the user. Do not display any error dialog.</p>
</item>
<item>
<title><code>IOErrorEnum.TOO_MANY_OPEN_FILES</code></title>
  <p>The current process has too many files
    open and can't open any more. Duplicate descriptors do count toward
    this limit. Since 2.20</p>
</item>
<item>
<title><code>IOErrorEnum.NOT_INITIALIZED</code></title>
  <p>The object has not been initialized. Since 2.22</p>
</item>
<item>
<title><code>IOErrorEnum.ADDRESS_IN_USE</code></title>
  <p>The requested address is already in use. Since 2.22</p>
</item>
<item>
<title><code>IOErrorEnum.PARTIAL_INPUT</code></title>
  <p>Need more input to finish operation. Since 2.24</p>
</item>
<item>
<title><code>IOErrorEnum.INVALID_DATA</code></title>
  <p>The input data was invalid. Since 2.24</p>
</item>
<item>
<title><code>IOErrorEnum.DBUS_ERROR</code></title>
  <p>A remote object generated an error that
    doesn't correspond to a locally registered <link href="../GLib-2.0/GLib.Error.html">GLib.Error</link> error
    domain. Use <link xref="Gio.dbus_error_get_remote_error"/> to extract the D-Bus
    error name and <link xref="Gio.dbus_error_strip_remote_error"/> to fix up the
    message so it matches what was received on the wire. Since 2.26.</p>
</item>
<item>
<title><code>IOErrorEnum.HOST_UNREACHABLE</code></title>
  <p>Host unreachable. Since 2.26</p>
</item>
<item>
<title><code>IOErrorEnum.NETWORK_UNREACHABLE</code></title>
  <p>Network unreachable. Since 2.26</p>
</item>
<item>
<title><code>IOErrorEnum.CONNECTION_REFUSED</code></title>
  <p>Connection refused. Since 2.26</p>
</item>
<item>
<title><code>IOErrorEnum.PROXY_FAILED</code></title>
  <p>Connection to proxy server failed. Since 2.26</p>
</item>
<item>
<title><code>IOErrorEnum.PROXY_AUTH_FAILED</code></title>
  <p>Proxy authentication failed. Since 2.26</p>
</item>
<item>
<title><code>IOErrorEnum.PROXY_NEED_AUTH</code></title>
  <p>Proxy server needs authentication. Since 2.26</p>
</item>
<item>
<title><code>IOErrorEnum.PROXY_NOT_ALLOWED</code></title>
  <p>Proxy connection is not allowed by ruleset.
    Since 2.26</p>
</item>
<item>
<title><code>IOErrorEnum.BROKEN_PIPE</code></title>
  <p>Broken pipe. Since 2.36</p>
</item>
</terms>
  <links type="topic" ui:expanded="true"
         api:type="function" api:mime="text/x-gjs"
         groups="function" style="linklist">
    <title>Functions</title>
  </links>
</page>
